/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HostRouteImport } from './routes/host'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as RequestsRequestIdRouteImport } from './routes/requests.$requestId'
import { Route as VillasVillaIdRouteImport } from './routes/villas.$villaId'
import { Route as YourStayStayIdRouteImport } from './routes/your-stay.$stayId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRequestIdRoute = RequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const VillasVillaIdRoute = VillasVillaIdRouteImport.update({
  id: '/villas/$villaId',
  path: '/villas/$villaId',
  getParentRoute: () => rootRouteImport,
} as any)
const YourStayStayIdRoute = YourStayStayIdRouteImport.update({
  id: '/your-stay/$stayId',
  path: '/your-stay/$stayId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/host': typeof HostRoute
  '/ops': typeof OpsRoute
  '/sale': typeof SaleRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/villas/$villaId': typeof VillasVillaIdRoute
  '/your-stay/$stayId': typeof YourStayStayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/host': typeof HostRoute
  '/ops': typeof OpsRoute
  '/sale': typeof SaleRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/villas/$villaId': typeof VillasVillaIdRoute
  '/your-stay/$stayId': typeof YourStayStayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/host': typeof HostRoute
  '/ops': typeof OpsRoute
  '/sale': typeof SaleRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/villas/$villaId': typeof VillasVillaIdRoute
  '/your-stay/$stayId': typeof YourStayStayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/host'
    | '/ops'
    | '/sale'
    | '/requests/$requestId'
    | '/villas/$villaId'
    | '/your-stay/$stayId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/host'
    | '/ops'
    | '/sale'
    | '/requests/$requestId'
    | '/villas/$villaId'
    | '/your-stay/$stayId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/host'
    | '/ops'
    | '/sale'
    | '/requests/$requestId'
    | '/villas/$villaId'
    | '/your-stay/$stayId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HostRoute: typeof HostRoute
  OpsRoute: typeof OpsRoute
  SaleRoute: typeof SaleRoute
  RequestsRequestIdRoute: typeof RequestsRequestIdRoute
  VillasVillaIdRoute: typeof VillasVillaIdRoute
  YourStayStayIdRoute: typeof YourStayStayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$requestId': {
      id: '/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof RequestsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villas/$villaId': {
      id: '/villas/$villaId'
      path: '/villas/$villaId'
      fullPath: '/villas/$villaId'
      preLoaderRoute: typeof VillasVillaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/your-stay/$stayId': {
      id: '/your-stay/$stayId'
      path: '/your-stay/$stayId'
      fullPath: '/your-stay/$stayId'
      preLoaderRoute: typeof YourStayStayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HostRoute: HostRoute,
  OpsRoute: OpsRoute,
  SaleRoute: SaleRoute,
  RequestsRequestIdRoute: RequestsRequestIdRoute,
  VillasVillaIdRoute: VillasVillaIdRoute,
  YourStayStayIdRoute: YourStayStayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
