/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HostRouteImport } from './routes/host'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as AdminImagesRouteImport } from './routes/admin_.images'
import { Route as AdminLinksRouteImport } from './routes/admin_.links'
import { Route as AdminRolesRouteImport } from './routes/admin_.roles'
import { Route as DevAccountsRouteImport } from './routes/dev.accounts'
import { Route as RequestsRequestIdRouteImport } from './routes/requests.$requestId'
import { Route as VillasVillaIdRouteImport } from './routes/villas.$villaId'
import { Route as YourStayStayIdRouteImport } from './routes/your-stay.$stayId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImagesRoute = AdminImagesRouteImport.update({
  id: '/admin_/images',
  path: '/admin/images',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/admin_/links',
  path: '/admin/links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin_/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAccountsRoute = DevAccountsRouteImport.update({
  id: '/dev/accounts',
  path: '/dev/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRequestIdRoute = RequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const VillasVillaIdRoute = VillasVillaIdRouteImport.update({
  id: '/villas/$villaId',
  path: '/villas/$villaId',
  getParentRoute: () => rootRouteImport,
} as any)
const YourStayStayIdRoute = YourStayStayIdRouteImport.update({
  id: '/your-stay/$stayId',
  path: '/your-stay/$stayId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/host': typeof HostRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/sale': typeof SaleRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/roles': typeof AdminRolesRoute
  '/dev/accounts': typeof DevAccountsRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/villas/$villaId': typeof VillasVillaIdRoute
  '/your-stay/$stayId': typeof YourStayStayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/host': typeof HostRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/sale': typeof SaleRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/roles': typeof AdminRolesRoute
  '/dev/accounts': typeof DevAccountsRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/villas/$villaId': typeof VillasVillaIdRoute
  '/your-stay/$stayId': typeof YourStayStayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/host': typeof HostRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/sale': typeof SaleRoute
  '/admin_/images': typeof AdminImagesRoute
  '/admin_/links': typeof AdminLinksRoute
  '/admin_/roles': typeof AdminRolesRoute
  '/dev/accounts': typeof DevAccountsRoute
  '/requests/$requestId': typeof RequestsRequestIdRoute
  '/villas/$villaId': typeof VillasVillaIdRoute
  '/your-stay/$stayId': typeof YourStayStayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/host'
    | '/login'
    | '/ops'
    | '/sale'
    | '/admin/images'
    | '/admin/links'
    | '/admin/roles'
    | '/dev/accounts'
    | '/requests/$requestId'
    | '/villas/$villaId'
    | '/your-stay/$stayId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/host'
    | '/login'
    | '/ops'
    | '/sale'
    | '/admin/images'
    | '/admin/links'
    | '/admin/roles'
    | '/dev/accounts'
    | '/requests/$requestId'
    | '/villas/$villaId'
    | '/your-stay/$stayId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/host'
    | '/login'
    | '/ops'
    | '/sale'
    | '/admin_/images'
    | '/admin_/links'
    | '/admin_/roles'
    | '/dev/accounts'
    | '/requests/$requestId'
    | '/villas/$villaId'
    | '/your-stay/$stayId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HostRoute: typeof HostRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRoute
  SaleRoute: typeof SaleRoute
  AdminImagesRoute: typeof AdminImagesRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminRolesRoute: typeof AdminRolesRoute
  DevAccountsRoute: typeof DevAccountsRoute
  RequestsRequestIdRoute: typeof RequestsRequestIdRoute
  VillasVillaIdRoute: typeof VillasVillaIdRoute
  YourStayStayIdRoute: typeof YourStayStayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/images': {
      id: '/admin_/images'
      path: '/admin/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof AdminImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/links': {
      id: '/admin_/links'
      path: '/admin/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/roles': {
      id: '/admin_/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/accounts': {
      id: '/dev/accounts'
      path: '/dev/accounts'
      fullPath: '/dev/accounts'
      preLoaderRoute: typeof DevAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$requestId': {
      id: '/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof RequestsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villas/$villaId': {
      id: '/villas/$villaId'
      path: '/villas/$villaId'
      fullPath: '/villas/$villaId'
      preLoaderRoute: typeof VillasVillaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/your-stay/$stayId': {
      id: '/your-stay/$stayId'
      path: '/your-stay/$stayId'
      fullPath: '/your-stay/$stayId'
      preLoaderRoute: typeof YourStayStayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HostRoute: HostRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRoute,
  SaleRoute: SaleRoute,
  AdminImagesRoute: AdminImagesRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminRolesRoute: AdminRolesRoute,
  DevAccountsRoute: DevAccountsRoute,
  RequestsRequestIdRoute: RequestsRequestIdRoute,
  VillasVillaIdRoute: VillasVillaIdRoute,
  YourStayStayIdRoute: YourStayStayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
